// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args)
	 {
		int numTest =  Integer.parseInt(args[0]);
		double num1 = 0;
		int i = 0 , j =0;
		while(numTest > 0)
		{
		num1 = (Math.random());
			if(num1 <= 0.5)
			{
				i++;
			}else{
				j++;
			}
		numTest--;
		}
		double ratio = 0;
		if(i>j)
		{
			ratio = (double)j/(double)i;
		}else{
		 ratio = (double)i/(double)j;
		}
		System.out.println("> 0.5:  " + j + " times");
		System.out.println("<= 0.5: " + i + " times");
		if(ratio != 0)
		{
		System.out.println("Ratio:  " + ratio);
		}

	    // Replace this comment with your code
	}
}
